// Code generated by MockGen. DO NOT EDIT.
// Source: session.go

// Package mock_drouter is a generated GoMock package.
package mocked_disgord

import (
	disgord "github.com/andersfylling/disgord"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockrouterSession is a mock of routerSession interface
type MockrouterSession struct {
	ctrl     *gomock.Controller
	recorder *MockrouterSessionMockRecorder
}

// MockrouterSessionMockRecorder is the mock recorder for MockrouterSession
type MockrouterSessionMockRecorder struct {
	mock *MockrouterSession
}

// NewMockrouterSession creates a new mock instance
func NewMockrouterSession(ctrl *gomock.Controller) *MockrouterSession {
	mock := &MockrouterSession{ctrl: ctrl}
	mock.recorder = &MockrouterSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockrouterSession) EXPECT() *MockrouterSessionMockRecorder {
	return m.recorder
}

// Myself mocks base method
func (m *MockrouterSession) Myself() (*disgord.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Myself")
	ret0, _ := ret[0].(*disgord.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Myself indicates an expected call of Myself
func (mr *MockrouterSessionMockRecorder) Myself() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Myself", reflect.TypeOf((*MockrouterSession)(nil).Myself))
}

// SendMsg mocks base method
func (m *MockrouterSession) SendMsg(channelID disgord.Snowflake, message *disgord.Message) (*disgord.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", channelID, message)
	ret0, _ := ret[0].(*disgord.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMsg indicates an expected call of SendMsg
func (mr *MockrouterSessionMockRecorder) SendMsg(channelID, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockrouterSession)(nil).SendMsg), channelID, message)
}

// SendMsgString mocks base method
func (m *MockrouterSession) SendMsgString(channelID disgord.Snowflake, content string) (*disgord.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsgString", channelID, content)
	ret0, _ := ret[0].(*disgord.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMsgString indicates an expected call of SendMsgString
func (mr *MockrouterSessionMockRecorder) SendMsgString(channelID, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsgString", reflect.TypeOf((*MockrouterSession)(nil).SendMsgString), channelID, content)
}
