sudo: enabled

language: go

go_import_path: github.com/NyanKiyoshi/disgord-plugin-router

go:
  - "1.10.x"
  - "1.11.x"
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

install:
  - "sudo python -m pip install codecov"
  - "go get -t -v ./..."

script:
  - "go test -race \
        -covermode=atomic \
        -coverpkg=./ \
        -coverprofile=coverage.txt \
        -tags test \
        ./"

after_success:
  - "python -m codecov"
